### ISSUE TITLE
Plan better way to pass PlayerInfo

### ISSUE THREAD

**Issue by QUzair** [FernAcular/StrongholdSiege#25]
Currently we drag and drop Player class into Strongholds.
Created a third class (EmptyStronghold) to get rid of NULLExceptionError, since you cannot have an un-instantiated Object. 

Currently requires every stronghold to have a Player GameObject dragged in (Wouldn't be best for scaling strongholds). 

Need to figure way to allow prefab to have default player settings and only two strongholds to require drag and drop.

**Comment by salahusama** [comment]
Talked IRL. This issue was resolved.
