### ISSUE TITLE
Changing Build Target

### ISSUE THREAD

**Issue by QUzair** [FernAcular/StrongholdSiege#50]
Its better to create this project initially with the build target for mobile (iOS/Android) rather than PC OS, since it will be easier for testing and initial deployment.

**Comment by salahusama** [comment]
I unassigned everyone, if you're free please take it on. @QUzair, is this blocking #43? If not, I think we can push this back to the backlog since we're setting weekly targets to what's in `Ready`.

If it's blocking it though, lets try close this task this week :D

**Comment by QUzair** [comment]
Well its a group decision as it will affect the rest of the code as well. It wont block #43 but that issue may need to be modified as the camera and canvas commands for mobile are different

**Comment by salahusama** [comment]
Alright then. Should we push it back to the backlog and discuss it in the meeting on Friday?

**Comment by QUzair** [comment]
Done
